BUNDLES = [
    "//apps/intentx/api:onos-apps-intentx-api",
    "//apps/intentx/app:onos-apps-intentx-app",
]

onos_app(
    category = "Traffic Steering",
    description = "Intent Extend",
    included_bundles = BUNDLES,
    title = "Intent Extension",
    url = "https://www.ict.com",
)
